/**
 * The look of every area: sky, fog, floors, walls, the fluid under the path and
 * which scenery props line it. Colours lean bright and saturated, like the
 * original Roblox map (lavender diamond-plate paths, pink brick cliffs with
 * grass tops, blue sea).
 *
 *   sky: [zenith, horizon], night: stars in the sky
 *   floor / floor2: the runway colours (alternating segments), pattern: texture
 *   wall / wallTop: scenery cliffs and their caps
 *   trim: edge rails and arches, accent: signs and glow
 *   fluid: water | lava | acid | void | candy | cloud
 *   props: scenery generators (see world/Scenery.jsx)
 */
export const THEMES = {
  lobby: {
    sky: ['#2f8ff0', '#d6ebfa'],
    fog: '#d6ebfa',
    floor: '#aab4ff',
    floor2: '#8fe36b',
    pattern: 'diamond',
    wall: '#e46a7a',
    wallTop: '#6fdc4f',
    trim: '#5a6aff',
    accent: '#ffd23f',
    fluid: 'water',
    props: ['trees', 'cliffs'],
    sun: '#fff6d0',
  },
  sakura: {
    sky: ['#3a95f0', '#ffe0ee'],
    fog: '#ffd6ea',
    floor: '#aab4ff',
    floor2: '#8fe36b',
    pattern: 'diamond',
    wall: '#e46a7a',
    wallTop: '#6fdc4f',
    trim: '#ff7ab0',
    accent: '#ff7ab0',
    fluid: 'water',
    props: ['sakura', 'cliffs', 'torii'],
  },
  bamboo: {
    sky: ['#2fa0ff', '#d4f4ff'],
    fog: '#d4f4ff',
    floor: '#c8d88a',
    floor2: '#8fd36b',
    pattern: 'planks',
    wall: '#5aa84a',
    wallTop: '#9be36b',
    trim: '#2f8a3a',
    accent: '#ffd23f',
    fluid: 'water',
    props: ['bamboo', 'islands', 'lanterns'],
  },
  desert: {
    sky: ['#3a9cf0', '#ffe2b8'],
    fog: '#ffd9b0',
    floor: '#f2c79a',
    floor2: '#aab4ff',
    pattern: 'studs',
    wall: '#e8a86a',
    wallTop: '#f6d4a0',
    trim: '#c87a3a',
    accent: '#ffb21f',
    fluid: 'quicksand',
    props: ['dunes', 'pyramids', 'palms'],
  },
  pirate: {
    sky: ['#3a8cff', '#c8f0ff'],
    fog: '#bfe8ff',
    floor: '#5a5fe0',
    floor2: '#c89a6a',
    pattern: 'diamond',
    wall: '#4a5ac8',
    wallTop: '#6fdc4f',
    trim: '#8a5a2a',
    accent: '#ffd23f',
    fluid: 'water',
    props: ['ships', 'islands', 'palms', 'swords'],
  },
  volcano: {
    sky: ['#3a0a0a', '#ff7a3a'],
    fog: '#a8401f',
    floor: '#4a3a3a',
    floor2: '#6a4a3a',
    pattern: 'bricks',
    wall: '#2a1a1a',
    wallTop: '#ff5a1f',
    trim: '#ff6a1f',
    accent: '#ff8a1f',
    fluid: 'lava',
    props: ['volcanoes', 'rocks', 'cliffs'],
    glowTop: true,
  },
  ice: {
    sky: ['#3f9af0', '#eef2ff'],
    fog: '#eee8ff',
    floor: '#dff4ff',
    floor2: '#9fd8ff',
    pattern: 'studs',
    wall: '#9fd0ff',
    wallTop: '#ffffff',
    trim: '#4fb8ff',
    accent: '#7fd8ff',
    fluid: 'water',
    props: ['mountains', 'pines', 'icespikes'],
  },
  ninja: {
    float: true,
    sky: ['#0a0a2a', '#4a2a6a'],
    fog: '#3a2050',
    floor: '#9a9ac0',
    floor2: '#8a5a4a',
    pattern: 'roof',
    wall: '#3a2a4a',
    wallTop: '#c83a3a',
    trim: '#e0303a',
    accent: '#ff4a5a',
    fluid: 'void',
    props: ['pagodas', 'lanterns', 'moon'],
    night: true,
  },
  crystal: {
    sky: ['#1a0a3a', '#7a4aaa'],
    fog: '#5a3a8a',
    floor: '#a89ad8',
    floor2: '#b88ad8',
    pattern: 'studs',
    wall: '#4a2a7a',
    wallTop: '#e04bd8',
    trim: '#e04bd8',
    accent: '#ff7af0',
    fluid: 'acid',
    props: ['crystals', 'cliffs'],
    night: true,
  },
  storm: {
    sky: ['#2a3040', '#8a9ab0'],
    fog: '#7a8aa0',
    floor: '#a8b0c8',
    floor2: '#7a8a6a',
    pattern: 'diamond',
    wall: '#4a5060',
    wallTop: '#6a8a5a',
    trim: '#ffe23a',
    accent: '#ffe23a',
    fluid: 'water',
    props: ['rods', 'mountains', 'rocks'],
  },
  swamp: {
    sky: ['#2a4a2a', '#b8d890'],
    fog: '#9ab870',
    floor: '#7a8a5a',
    floor2: '#5a6a3a',
    pattern: 'planks',
    wall: '#3a4a2a',
    wallTop: '#7ac83a',
    trim: '#9dff2a',
    accent: '#9dff2a',
    fluid: 'acid',
    props: ['deadtrees', 'mushrooms', 'islands'],
  },
  sky: {
    float: true,
    sky: ['#6aa8ff', '#fff0fa'],
    fog: '#f4fbff',
    floor: '#ffffff',
    floor2: '#ffe8a8',
    pattern: 'diamond',
    wall: '#f0f4ff',
    wallTop: '#ffd23f',
    trim: '#ffc21f',
    accent: '#ffd23f',
    fluid: 'cloud',
    props: ['columns', 'cloudisles'],
  },
  shadow: {
    sky: ['#3a1a6a', '#b07ae8'],
    fog: '#6a3a9a',
    floor: '#8a7ad8',
    floor2: '#6a5ab8',
    pattern: 'bricks',
    wall: '#3a2a5a',
    wallTop: '#8a2aff',
    trim: '#a43aff',
    accent: '#c86aff',
    fluid: 'void',
    props: ['spires', 'crystals'],
    night: true,
    glowTop: true,
  },
  neon: {
    float: true,
    sky: ['#2a1a6a', '#8a5ae0'],
    fog: '#4a2a8a',
    floor: '#6a7ae0',
    floor2: '#5a5ac0',
    pattern: 'diamond',
    wall: '#2a2a54',
    wallTop: '#00e5ff',
    trim: '#ff00d4',
    accent: '#00e5ff',
    fluid: 'void',
    props: ['towers'],
    night: true,
    glowTop: true,
  },
  dragon: {
    sky: ['#5a1a0a', '#ffb06a'],
    fog: '#e08a5a',
    floor: '#8a6a5a',
    floor2: '#6a4a3a',
    pattern: 'bricks',
    wall: '#5a3a2a',
    wallTop: '#c83a1a',
    trim: '#ffb21f',
    accent: '#ff5a1f',
    fluid: 'lava',
    props: ['volcanoes', 'spikes', 'mountains'],
  },
  coral: {
    sky: ['#2a8cff', '#b8f4ff'],
    fog: '#9af0ff',
    floor: '#f6e0b0',
    floor2: '#7ad8ff',
    pattern: 'studs',
    wall: '#ff7a8a',
    wallTop: '#ffd0a0',
    trim: '#ff5a8a',
    accent: '#ff8ab0',
    fluid: 'water',
    props: ['corals', 'palms'],
  },
  candy: {
    float: true,
    sky: ['#ff8ad0', '#fff4fc'],
    fog: '#ffe6f6',
    floor: '#ffd6ec',
    floor2: '#c8f0ff',
    pattern: 'checker',
    wall: '#ff8ac8',
    wallTop: '#ffffff',
    trim: '#ff4fa8',
    accent: '#ff4fa8',
    fluid: 'candy',
    props: ['lollipops', 'gumdrops'],
  },
  ghost: {
    float: true,
    sky: ['#0a0a1a', '#4a5a7a'],
    fog: '#3a4a6a',
    floor: '#a0a0b8',
    floor2: '#80809a',
    pattern: 'bricks',
    wall: '#2a2a3a',
    wallTop: '#5a6a8a',
    trim: '#e03a3a',
    accent: '#7af0ff',
    fluid: 'void',
    props: ['torii', 'deadtrees', 'lanterns', 'moon'],
    night: true,
  },
  galaxy: {
    float: true,
    sky: ['#000008', '#1a0a4a'],
    fog: '#0a0628',
    floor: '#6a5ac8',
    floor2: '#4a3aa0',
    pattern: 'diamond',
    wall: '#1a0a4a',
    wallTop: '#ff00d4',
    trim: '#00e5ff',
    accent: '#ff00d4',
    fluid: 'void',
    props: ['planets', 'crystals'],
    night: true,
    glowTop: true,
  },
  heaven: {
    float: true,
    sky: ['#ffc86a', '#fff8f0'],
    fog: '#fff6e0',
    floor: '#fff6e0',
    floor2: '#ffe28a',
    pattern: 'diamond',
    wall: '#fff0c8',
    wallTop: '#ffd23f',
    trim: '#ffb800',
    accent: '#ffd700',
    fluid: 'cloud',
    props: ['columns', 'cloudisles'],
  },
  castle: {
    sky: ['#1a0005', '#8a1a1a'],
    fog: '#4a0a10',
    floor: '#7a6a7a',
    floor2: '#8a4a4a',
    pattern: 'bricks',
    wall: '#2a1a24',
    wallTop: '#e01a2a',
    trim: '#ffd23f',
    accent: '#ff2a3a',
    fluid: 'lava',
    props: ['castles', 'spikes', 'volcanoes'],
    night: true,
    glowTop: true,
  },
}

export const themeOf = (key) => THEMES[key] || THEMES.lobby
